### ISSUE TITLE
Rename binary to iqtree2

### ISSUE THREAD

**Issue by tseemann** [Cibiv/IQ-TREE#131]
iqtree 1.x is already a major part of many workflows around the worls

iqtree 2.x breaks all command line compatibility.

Would you consider using `iqtree2` as the binary name so the two versions can live in harmony and not cause chaos around the world like python2/3 (and many other tools) did? 

Thank you  :)

**Comment by bqminh** [comment]
It makes sense to change binary to iqtree2 because of many changes and improvements. I'll do that in v2.0.4.
I just want to note that it does not break any command lines -- all options in v1 are still valid in v2. Only that a few options have a new (and better) name, but the old options still work as it is: they are synonymous. For example, -B is for ultrafast bootstrap and -bb still works in v2. They it is backward compatible.

**Comment by bqminh** [comment]
Done, now in v2.0.4
