### ISSUE TITLE
Even when specifying the RNG seed, the outcome is not deterministic

### ISSUE THREAD

**Issue by Cyoung02** [Cibiv/IQ-TREE#191]
It seems like even when a seed is specified, likelihood scores differ slightly (see lines 35 and 36 on the two log files I've attached). 

Is this a bug or intended behavior? 

[Here](https://github.com/Cibiv/IQ-TREE/files/6079582/IQTREE.zip) are the input alignment and log files for both runs. 

Thanks!

**Comment by heikotree** [comment]
Dear Colin Young,

As soon as you are running analysis in parallel this is expected to happen, because the load of your infrastructure does influence the order in which the parallel tasks and computation are finished and incorporated which might cause different rounding effects and subsequently sometimes slightly different decisions.

This order cannot be controlled by the seed.

Only when running with only one core, the behaviour should be deterministic.

Thus, this neither a bug not intended behaviour, but an expected behaviour.

Best wishes,
Heiko


> On 03.03.2021, at 23:37, Colin Young <notifications@github.com> wrote:
> 
> 
> It seems like even when a seed is specified, likelihood scores differ slightly (see lines 35 and 36 on the two log files I've attached).
> 
> Is this a bug or intended behavior?
> 
> Here are the input alignment and log files for both runs.
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-----------------------------------------------------------------------------
Heiko Schmidt
Center for Integrative Bioinformatics Vienna (CIBIV) 
University of Vienna / Max Perutz Labs
Campus Vienna Biocenter 5 (VBC5)
A-1030 Vienna, Austria
-----------------------------------------------------------------------------
Email: heiko.schmidt(AT)univie.ac.at
Tel. :  ++43 +1 / 4277 - 74321
http://www.cibiv.at/
-----------------------------------------------------------------------------

**Comment by Cyoung02** [comment]
Ah that makes sense. Thanks for the clarification!
