### ISSUE TITLE
Printing more alignment statistics

### ISSUE THREAD

**Issue by bqminh** [Cibiv/IQ-TREE#34]
This would be useful for some users, e.g.:

* Which sites are informative?

TODO: Output format?

**Comment by uqfgaiti** [comment]
Just an idea, perhaps adding an extra column in the .rate file? 

Assuming that we used a Gamma rate heterogeneity model with 4 categories, the columns of .rate file would be the following:

Site:                   Column number of alignment file, starting from 1.
Rate:                  Evolutionary rate of the site inferred by empirical Bayesian method (or posterior mean).
Category:           The index of the Gamma category that this site likely falls into (with highest posterior probability). Category 1 means that the site is slowly evolving whereas category 4 means fast evolving. Thus, you can use this column to quickly classify the sites in the alignment.
Categorized_rate: The rate of the corresponding category.
**Informative: Y or N.** 

Or something on this line. 

Let me know what you think

Thanks
Fede

**Comment by heikotree** [comment]
Adding one column to the .rate-file would be one possiblility, but that means that if one is only interested in the (parsimony) informativeness one always has to output all the rates as well.

I also had two suggestions, which both have their advantages:

First for the coding I suggest a slightly more distinguishing notation:
I = informative;
U = variable, but uninformative;
C = completely constant, that means exactly one (determined) character like A,C,G,T in DNA;
c = constant, but contains also gaps and wildcards (like N, X, R, Y)
The latter (c) is already counted as constant in the IQ-Tree output.
Possibly we should also add X for columns that contain only gaps and wildcards.

(a) one file with two columns one for the site (yes, starting from 1 - to make the non-compter-scientists happy) and another one for the informativeness. 

(b) a file with a single line consisting "info" (plus >= 6 spaces) at start and than one character per site (IUcC) as defined above.
This line can than be incorporated into a multiple sequence alignment such that one can highlight or/and scrutinize columns by their information tag.

(c) as an alternative to (b) one could output a 'marked' alignment, that contains the 'info-sequence' described in (b).

What do you think?

Cheers,
Heiko

**Comment by bqminh** [comment]
@uqfgaiti: One should use a different file, because .rate file is only generated if you specify -wsr option AND the model must be with +G or +R. Thus, a separate file is preferable with a suffix like .alnstats

@heikotree : the encoding sounds like a good idea, as one can represent it compactly in a sequence in (b). Outputting either (a) or (b) is fine - I have no strong opinion which one...

Moreover, we should also think about partition model case: how does the output looks like in case of several partitions?

Minh

**Comment by uqfgaiti** [comment]
Thanks guys,

I like the encoding idea. Either (a) or (b) would be fine. And thanks for making the non-compeer-scientists happy ;)

Cheers
Fede

On Aug 3, 2017, at 3:05 AM, Bui Quang Minh <notifications@github.com<mailto:notifications@github.com>> wrote:


@uqfgaiti<https://github.com/uqfgaiti>: One should use a different file, because .rate file is only generated if you specify -wsr option AND the model must be with +G or +R. Thus, a separate file is preferable with a suffix like .alnstats

@heikotree<https://github.com/heikotree> : the encoding sounds like a good idea, as one can represent it compactly in a sequence in (b). Outputting either (a) or (b) is fine - I have no strong opinion which one...

Moreover, we should also think about partition model case: how does the output looks like in case of several partitions?

Minh

**Comment by bqminh** [comment]
DONE with v1.6, commit 8625544a0
