### ISSUE TITLE
Empirical protein models should normalize fixed amino-acid frequencies

### ISSUE THREAD

**Issue by bredelings** [Cibiv/IQ-TREE#74]
Hi,

The fixed amino-acid frequencies supplied by models like WAG and LG do not actually sum to 1.0.  This doesn't really affect the rate matrix, since it is going to be rescaled to a fixed rate anyway.  However, the frequencies are also used to compute the likelihood at the root.  Therefore, I think it is not correct if the frequencies do not sum to 1.

It would be nice to fix this so that IQ-Tree passes the testiphy tests lg/2 and wag/2.  Tests with uniform frequencies or user-supplied frequencies that sum to 1 already pass.

**Comment by bqminh** [comment]
Hi Ben,

Do you mean the model definition in modelprotein.cpp?

I just checked again, they do indeed some to 1.0

Minh

**Comment by bqminh** [comment]
Hi Ben, I remember: when putting the WAG/LG model, I realised that the sum do not equal 1.0. So I manually change the last entry to fulfill the condition. I can now understand that one should rather re-normalise the frequencies the way you described, so that it's closer to the "unrounded" estimates from the original authors. Can you help introduce this change into IQ-TREE? (directly into this model definition code).

However, I think the original authors are to blame here. They actually should have had a version of the matrix with higher precision and should have reported that, instead of these rounded matrix. Nevertheless, I'm not sure how much that impact the likelihood computation (probably only at precision 6 or more).

**Comment by bqminh** [comment]
Fixed in commit 658020a
IMPORTANT: amino-acid frequencies of DAYHOFF, DCMUT, JTT, MTREV, WAG, CPREV, LG, MTZOA, PMB, JTTDCMUT, FLU are slightly modified with higher precision and normalised to 1.
